version: "3"

services:
  poll:
    depends_on:
      - redis
    build: ./poll
    restart: always
    ports:
    - 5000:80
    networks:
      - poll-tier
    environment:
      - 0.0.0.0

  redis:
    image: redis
    restart: always
    ports:
    - 6379:6379
    networks:
    - poll-tier
    - back-tier
  
  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    restart: always
    environment: 
      - 0.0.0.0
    networks:
      - back-tier
  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    networks: 
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql

  result:
    build: ./result
    depends_on:
      - db
    restart: always
    ports:
      - 5001:80
    networks:
      - result-tier
    environment:
    - 0.0.0.0

networks: 
  poll-tier:
  result-tier:
  back-tier:
volumes: 
  db-data:


